name: Pipeline de CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install flask coverage

      - name: Run Tests with Coverage
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Generate Coverage Report
        run: python -m coverage report

  security-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security Check (Simulation)
        run: |
          echo "Iniciando análise estática de segurança (SAST)..."
          echo "Nenhuma vulnerabilidade crítica encontrada."

  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build Simulation
        run: echo "Olá, ${{ github.actor }}! Construindo a aplicação..."
  
  deploy-prod-job:
    needs: [unit-tests, build-job] # Garante que só roda se os testes e o build passarem
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          echo "Implantando a branch ${{ github.ref_name }} em produção..."
          sleep 20
          echo "Implantação concluída com sucesso!"