name: Pipeline de CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install flask coverage

      - name: Run Tests with Coverage
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Generate Coverage Report
        run: python -m coverage report