name: Pipeline de CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Coverage Report
        run: |
          pip install coverage
          python -m coverage run -m unittest -v tests/appTest.py
          python -m coverage report